### ISSUE TITLE
Cannot work with rollup-plugin-typescript2

### ISSUE THREAD

**Issue by Val-istar-Guo** [bitshiftza/rollup-plugin-ts-paths#1]
alias path in .d.ts is not Replaced.

**Comment by bitshiftza** [comment]
Happy to spend time looking into this but please could you provide a sample to which reproduces this issue.

**Comment by Val-istar-Guo** [comment]
emmmm........ because the time is too long, I have forgotten what happened........ I used ttypescript to solve the problem.
